# Generated by Django 4.2.7 on 2026-07-11 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_feedback_e_evento_helpers'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='editada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='votos_inuteis',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes_inuteis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='votos_uteis',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes_uteis', to=settings.AUTH_USER_MODEL),
        ),
    ]
