# Generated by Django 4.2.7 on 2026-07-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_avaliacao_data_edicao_avaliacao_editada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='eventos/fotos/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.evento')),
            ],
            options={
                'verbose_name': 'Foto do Evento',
                'verbose_name_plural': 'Fotos dos Eventos',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
