# Generated by Django 4.2.7 on 2026-07-13 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fotoevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF'),
        ),
    ]
